Add Book - first version
prajdziswet/ExamplesUladzimir pull request #16
Opened 2021-05-07 06:53 UTC by prajdziswet

2021-05-07 15:07 UTC, alex-skiba-postnl requested changes

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +            Assert.IsTrue(lib.Books[0].AuthorBook == lib.AddAuthor("Lev", "Tolstoj"));
It's very wrong to **get** author by calling **Add** method. that's a violation of the development contract, please never do this.
In this specific case you already have `author` variable above, why won't use it?

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +            catch (NullReferenceException)
Please start using Shouldly. there's a dedicated way to check if specific exception was thrown: https://docs.shouldly.io/documentation/exceptions/throw#shouldthrowfunc

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/Library.cs
> +                throw new NullReferenceException("Одно из полей книги пусто");
There's `ArgumentNullException`

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/Library.cs
> +                throw new ArgumentException("Данная книга существует");
Please use English

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/Library.cs
> +                throw new NullReferenceException("Одно из полей книги пусто");
And please use English

2021-05-07 15:07 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +namespace ClassLibrary.Test
I think you've missed a test case when we add a valid Author which is not in the Library.

2021-05-10 04:30 UTC, prajdziswet commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +namespace ClassLibrary.Test
I think You're wrong
![image](https://user-images.githubusercontent.com/3761997/117605961-908c7400-b161-11eb-9116-e599f7ad58ab.png)

2021-05-10 04:30 UTC, prajdziswet commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +            Assert.IsTrue(lib.Books[0].AuthorBook == lib.AddAuthor("Lev", "Tolstoj"));
I agree, I just wanted to additionally check that this is one link.

2021-05-10 04:30 UTC, prajdziswet commented on ClassLibrary/ClassLibrary/Library.cs
> +                throw new ArgumentException("Данная книга существует");
Всетаки кирилица определяеться =))). Плохо не там где надо (I agree here), книги могут быть и на кирилице...

2021-05-10 06:41 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +namespace ClassLibrary.Test
I didn't express it correctly. Should've been "I think you've missed a test case when we add a Book with a valid Author which is not added to the Library."

2021-05-10 06:48 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestBooks.cs
> +            Assert.IsTrue(lib.Books[0].AuthorBook == lib.AddAuthor("Lev", "Tolstoj"));
almost always it's better to create a separate test case for it

2021-05-10 06:50 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/Library.cs
> +                throw new ArgumentException("Данная книга существует");
that's true, but figuring out encoding issues will take a lot of time. so let's just do it without cyrillic.

2021-05-11 07:48 UTC, alex-skiba-postnl approved these changes

2021-05-11 07:48 UTC, merged