Add ID and correct with it
prajdziswet/ExamplesUladzimir pull request #18
Opened 2021-05-23 05:58 UTC by prajdziswet

2021-05-23 20:00 UTC, alex-skiba-postnl requested changes

2021-05-23 20:00 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestRepositoryBooks.cs
> +            Should.Throw<ArgumentException>(() => RB.AddBook(book));
This change changes also the meaning of the test. "Adding the same book" and "adding a book with the same properties" are different cases, and there should be a test for each of them.

2021-05-23 20:00 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/Author.cs
> +        public bool EqualArgument(Author author) =>
`EqualArgument` is a meaningless name. You might override `Equals` which is a standard way of comparing objects, but difficult to implement properly: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-define-value-equality-for-a-type

Or you can just rename this method, but keep in mind that an additional comparison method confuses someone who will modify this code.

2021-05-23 20:00 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/RepositoryBooks.cs
> +                bool check=(bool) foundBooks?.Any(x=>x.NameBook!=book.NameBook||!x.AuthorBook.EqualArgument(book.AuthorBook));
`check` is a meaningless name for this variable. Even misleading.

2021-05-23 20:00 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/RepositoryBooks.cs
> +                foundBook = foundBooks?.FirstOrDefault(x => x.NameBook != book.NameBook || !x.AuthorBook.EqualArgument(book.AuthorBook));
This code can be merged with the initial check above

2021-05-23 20:00 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/RepositoryBooks.cs
> +                throw new ArgumentException($"This book with {book.ISBN} exist! Example is {foundBook.NameBook}-{foundBook.AuthorBook.Name}-{foundBook.AuthorBook.Name}");
Please make the error message more clear - if I read the code correctly the problem is not with an existing book, but that the existing book has different properties.

2021-05-24 06:19 UTC, prajdziswet commented on ClassLibrary/ClassLibrary/RepositoryBooks.cs
> +                foundBook = foundBooks?.FirstOrDefault(x => x.NameBook != book.NameBook || !x.AuthorBook.EqualArgument(book.AuthorBook));
?

2021-05-24 06:19 UTC, prajdziswet commented on ClassLibrary/ClassLibrary/Author.cs
> +        public bool EqualArgument(Author author) =>
Не совсем понял:
1) Стандартный метод Equals сравнівает только ссылки, названием метода я хотел показать что сравниваються значения (уникальный ключ не сравниваеться)
2) Трудно перевариваемая информация, даж в русской версии, например: "Two variables should be deemed equal only if the run-time types of the variables being compared are the same."
3) Относиться и к первому, по переименованию: например хочу реализовать ToString, но меня смущает факт что для всех типов он существует, и может сбивать с толку (поэтому не хочеться перегружать методы которые существуют) - в коммите он будет

2021-05-24 06:19 UTC, prajdziswet commented on ClassLibrary/ClassLibrary.Test/TestRepositoryBooks.cs
> +            Should.Throw<ArgumentException>(() => RB.AddBook(book));
please, when you choose specific test with common idea (or for reason), choose and name test => it makes it easier to find.. 
![image](https://user-images.githubusercontent.com/3761997/119298850-804abd80-bc66-11eb-9aa7-de182c2ee34d.png)
- example I have difference (maybe you look not last commit)

2021-05-24 14:12 UTC, alex-skiba-postnl requested changes

2021-05-24 14:12 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestRepositoryBooks.cs
> +        [TestCase("226611156", "War and Peace",0)]
Doesn't look like TestCase is needed here, just check both books in Asset area.

2021-05-24 14:12 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary.Test/TestRepositoryBooks.cs
> +        [TestCase("226611156", "War and Peace",0)]
And now I see that this test is the same as `AddBookEqualISBN`

2021-05-25 05:08 UTC, prajdziswet commented on ClassLibrary/ClassLibrary/RepositoryBooks.cs
> +                foundBook = foundBooks?.FirstOrDefault(x => x.NameBook != book.NameBook || !x.AuthorBook.EqualArgument(book.AuthorBook));
I cann't can be merged with the initial check above, because different check (condition)

2021-05-25 05:08 UTC, prajdziswet commented on ClassLibrary/ClassLibrary.Test/TestRepositoryBooks.cs
> +        [TestCase("226611156", "War and Peace",0)]
I did, but I disagree with you. 
because I think with TestCase code more simple and cleaver (better understood)

2021-05-25 09:01 UTC, alex-skiba-postnl approved these changes

2021-05-25 09:02 UTC, merged