Inhenit
prajdziswet/ExamplesUladzimir pull request #21
Opened 2021-06-02 06:37 UTC by prajdziswet

2021-06-06 08:56 UTC, alex-skiba-postnl requested changes

2021-06-06 08:56 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/BorrowedBook.cs
> +        public BorrowedBook(Book book):base(book.ISBN,book.NameBook,book.AuthorBook)
that's a mixture of inheritance and composition, we don't do this. to implement it with inheritance, you have to create all new books **only** as `BorrowedBook`.
you can then treat those `BorrowedBook`s as `Book`s in places where `BorrowedBook.dateTime` is not needed.

2021-06-07 04:59 UTC, prajdziswet commented on ClassLibrary/ClassLibrary/BorrowedBook.cs
> +        public BorrowedBook(Book book):base(book.ISBN,book.NameBook,book.AuthorBook)
Чуть не понял:
1) <с конца> Почему я должен создавать взятые-книги, у меня они создаються только при выдаче читателю, дополнительные поля нет смысла хранить. Книга -это базовая сущность, а взятая-книга = только когда читатель ее взял.
2) Почему я не могу передавать сущность книга, наследуемому класу? (использовать условно микс):
а) большинство полей используеться в наследуемом классе, а если их будет не 3, а 10 допустим
б) в библиотеке почти везде оперируют понятием "просто книга", а не отдельными полями или "взятой книгой"
в) да я могу расписать все поля, а не передавать "книгу", но если у нас будет не одно место создания взятой книги, каждый раз разбирать поля? = считаю, лучше это делать ближе к сущности...
---
запушил с простыми полями (доп. конструктор)

2021-06-10 07:35 UTC, alex-skiba-postnl commented on ClassLibrary/ClassLibrary/BorrowedBook.cs
> +        public BorrowedBook(Book book):base(book.ISBN,book.NameBook,book.AuthorBook)
1. "Почему я должен создавать взятые-книги"
 - `base(book.ISBN,book.NameBook,book.AuthorBook)` этот код создает новую Book с новым ID. ты же не создаешь новую книгу, ты отдаешь существующую книгу читателю.
 -  `public new int ID` это хак для того, чтобы избавиться от наследования и скрыть тот факт, что создана новая книга. в таких случая `new` никогда не используется со своим кодом, только с тем который ты не можешь изменить. это ярчайший индикатор сломанного механизма наследования.

таким образом, простой ответ на этот вопрос - "потому что всё остальное просто гребля против течения - наследование есть, но все его механизмы специально сломаны (экземпляр базового типа хранится в наследнике, происходит клонирование, происходит переопределение полей в наследнике).

а вообще сейчас очевидно, что наследование здесь очень сложно применить, это просто неподходящий кейс.

2. "Почему я не могу передавать сущность книга, наследуемому класу?" это просто неправильно. то, что ты пытаешься сделать - наследование **экземпляров**, в шарпе такого нет. у нас есть только наследование **типов**. это значит, что `Object.ReferenceEquals(book, borrowedBook) == true`. ты не можешь создать объект, а потом создать его наследника так, чтобы это условие выполнялось - ты можешь только создать наследника и **привести** его к базовому типу когда нужно ("в библиотеке почти везде оперируют понятием "просто книга"")

2021-06-10 09:32 UTC, closed without merging